FROM alpine:3.12.0

RUN apk update && apk add \
	wget \
	influxdb --repository http://dl-2.alpinelinux.org/alpine/edge/community/

COPY health_check.sh health_check.sh

RUN wget https://dl.influxdata.com/telegraf/releases/telegraf-1.15.3_static_linux_amd64.tar.gz && \
	tar -xvf telegraf-1.15.3_static_linux_amd64.tar.gz && \
	rm telegraf-1.15.3_static_linux_amd64.tar.gz && \
	mv telegraf-1.15.3 telegraf

RUN mkdir -p etc/telegraf

COPY telegraf.conf etc/telegraf/telegraf.conf

RUN mkdir -p var/lib/influxdb

COPY influxdb.conf etc/influxdb.conf

COPY entrypoint.sh entrypoint.sh

ENTRYPOINT sh entrypoint.sh