apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  labels:
    app: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      restartPolicy: Always
      containers:
      - name: influxdb
        image: influxdb
        imagePullPolicy: Never
        livenessProbe:
            exec:
              command:
              - sh
              - health_check.sh
            initialDelaySeconds: 10
            periodSeconds: 10
        ports:
        - name: influxdb
          containerPort: 8086
        volumeMounts:
        - name: influxdb-pv
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-pv
        persistentVolumeClaim:
          claimName: influxdb-pv

---

apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  type: ClusterIP
  selector:
    app: influxdb
  ports:
  - name: influxdb
    port: 8086
    protocol: TCP
    targetPort: 8086

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi