FROM alpine:3.12.0

RUN apk update && apk add \
	mariadb \
	mariadb-client \
	wget

COPY health_check.sh health_check.sh

RUN mkdir -p /run/mysqld

COPY my.cnf /etc/my.cnf
RUN chmod 644 /etc/my.cnf

COPY entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

COPY wordpress.sql wordpress.sql

RUN wget https://dl.influxdata.com/telegraf/releases/telegraf-1.15.3_static_linux_amd64.tar.gz && \
	tar -xvf telegraf-1.15.3_static_linux_amd64.tar.gz && \
	rm telegraf-1.15.3_static_linux_amd64.tar.gz && \
	mv telegraf-1.15.3 telegraf

RUN mkdir -p etc/telegraf

COPY telegraf.conf etc/telegraf/telegraf.conf

EXPOSE 3306

ENTRYPOINT sh entrypoint.sh