FROM alpine:3.12.0

RUN apk update && apk add \
	wget \
	grafana --repository https://dl-cdn.alpinelinux.org/alpine/latest-stable/community/


COPY dashboards usr/share/grafana/conf/provisioning/dashboards
COPY datasource.yaml usr/share/grafana/conf/provisioning/datasources/datasource.yaml

RUN wget https://dl.influxdata.com/telegraf/releases/telegraf-1.15.3_static_linux_amd64.tar.gz && \
	tar -xvf telegraf-1.15.3_static_linux_amd64.tar.gz && \
	rm telegraf-1.15.3_static_linux_amd64.tar.gz && \
	mv telegraf-1.15.3 telegraf

RUN mkdir -p etc/telegraf

COPY telegraf.conf etc/telegraf/telegraf.conf

EXPOSE 3000

ENTRYPOINT telegraf/usr/bin/telegraf & \
			/usr/sbin/grafana-server --homepath=/usr/share/grafana