FROM alpine:3.12.0

RUN apk update && apk add \
	influxdb \
	grafana --repository=https://dl-cdn.alpinelinux.org/alpine/latest-stable/community/ \
	telegraf --repository http://dl-3.alpinelinux.org/alpine/edge/testing/