apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana
        imagePullPolicy: Never
        livenessProbe:
            exec:
              command:
              - sh
              - health_check.sh
            initialDelaySeconds: 10
            periodSeconds: 10
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared"
  name: grafana-service
  labels:
    app: grafana
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: grafana
  ports:
  - name: grafana
    port: 3000
    protocol: TCP
    targetPort: 3000
