FROM alpine:3.12.0

RUN apk update && apk add \
	nginx \
	openssl

COPY default.conf /etc/nginx/conf.d/default.conf

RUN openssl req -newkey rsa:4096 -nodes -x509 -days 365 \
	-subj '/C=KR/ST=Seoul/L=42cluster/O=42cursus/OU=ft_services/CN=locahost/emailAddress=tg911022@naver.com' \
	-keyout /etc/ssl/private/localhost.key -out /etc/ssl/certs/localhost.crt

RUN mkdir run/nginx

EXPOSE 80 443

# nginx start : /usr/sbin/nginx
# nginx stop : /usr/sbin/nginx -s quit

ENTRYPOINT /usr/sbin/nginx -g "daemon off;"

# image build : docker build -t nginx .
# container run : docker run -d -it -p 80:80 -p 443:443 nginx
# access background container terminal : docker exec -it [cntnr_id] /bin/sh

# DEL all cntnr : docker stop $(docker ps -a -q) | docker rm -f $(docker ps -a -q)
# DEL all image : docker rmi -f $(docker images -q)