FROM alpine:3.12.0

RUN apk update && apk add \
	nginx \
	openssl \
	wget

COPY health_check.sh health_check.sh

COPY default.conf /etc/nginx/conf.d/default.conf

RUN openssl req -newkey rsa:4096 -nodes -x509 -days 365 \
	-subj '/C=KR/ST=Seoul/L=42cluster/O=42cursus/OU=ft_services/CN=locahost/emailAddress=tg911022@naver.com' \
	-keyout /etc/ssl/private/localhost.key -out /etc/ssl/certs/localhost.crt

RUN mkdir run/nginx

RUN wget https://dl.influxdata.com/telegraf/releases/telegraf-1.15.3_static_linux_amd64.tar.gz && \
	tar -xvf telegraf-1.15.3_static_linux_amd64.tar.gz && \
	rm telegraf-1.15.3_static_linux_amd64.tar.gz && \
	mv telegraf-1.15.3 telegraf

RUN mkdir -p etc/telegraf

COPY telegraf.conf etc/telegraf/telegraf.conf

EXPOSE 80 443

ENTRYPOINT /telegraf/usr/bin/telegraf & \
			/usr/sbin/nginx -g "daemon off;"