FROM alpine:3.12.0

RUN apk update && apk add \
	nginx \
	php7 \
	php7-fpm \
	php7-mbstring \
	php7-session \
	php7-common \
	php7-iconv \
	php7-json \
	php7-gd \
	php7-curl \
	php7-xml \
	php7-mysqli \
	php7-imap \
	php7-cgi \
	fcgi \
	php7-pdo \
	php7-pdo_mysql \
	php7-soap \
	php7-xmlrpc \
	php7-posix \
	php7-mcrypt \
	php7-gettext \
	php7-ldap \
	php7-ctype \
	php7-dom \
	mysql-client \
	wget

COPY default.conf /etc/nginx/conf.d/default.conf

RUN mkdir run/nginx

RUN wget https://wordpress.org/latest.tar.gz && \
	tar -xvf latest.tar.gz && \
	rm latest.tar.gz && \
	mv wordpress /var/www/wordpress

COPY wp-config.php /var/www/wp-config.php

RUN wget https://dl.influxdata.com/telegraf/releases/telegraf-1.15.3_static_linux_amd64.tar.gz && \
	tar -xvf telegraf-1.15.3_static_linux_amd64.tar.gz && \
	rm telegraf-1.15.3_static_linux_amd64.tar.gz && \
	mv telegraf-1.15.3 telegraf

RUN mkdir -p etc/telegraf

COPY telegraf.conf etc/telegraf/telegraf.conf

EXPOSE 80

ENTRYPOINT /telegraf/usr/bin/telegraf & \
			/usr/sbin/php-fpm7 && \
			/usr/sbin/nginx -g "daemon off;"