FROM alpine:3.12.0

RUN apk update && apk add \
	nginx \
	openssl \
	php7 \
	php7-bcmath \
	php7-ctype \
	php7-curl \
	php7-fpm \
	php7-gd \
	php7-iconv \
	php7-intl \
	php7-json \
	php7-mbstring \
	php7-mcrypt \
	php7-mysqlnd \
	php7-opcache \
	php7-openssl \
	php7-pdo \
	php7-pdo_mysql \
	php7-pdo_pgsql \
	php7-pdo_sqlite \
	php7-phar \
	php7-posix \
	php7-session \
	php7-soap \
	php7-xml \
	php7-zip \
	wget

COPY default.conf /etc/nginx/conf.d/default.conf

RUN mkdir run/nginx

RUN wget https://wordpress.org/latest.tar.gz && \
	tar -xvf latest.tar.gz && \
	rm latest.tar.gz && \
	mv wordpress /var/lib/nginx/html/wordpress

COPY wp-config.php /var/lib/nginx/html/wordpress/wp-config.php

EXPOSE 5050

ENTRYPOINT /usr/sbin/php-fpm7 && \
		   /usr/sbin/nginx -g "daemon off;"