apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        livenessProbe:
            exec:
              command:
              - sh
              - health_check.sh
            initialDelaySeconds: 10
            periodSeconds: 10
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002

---

apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "shared"
  name: ftps-service
  labels:
    app: ftps
spec:
  type: LoadBalancer
  loadBalancerIP: MINIKUBE_IP
  selector:
    app: ftps
  ports:
  - name: ftps-data
    port: 20
    targetPort: 20
  - name: ftps-server
    port: 21
    targetPort: 21
  - name: ftps-psv0
    port: 21000
    targetPort: 21000
  - name: ftps-psv1
    port: 21001
    targetPort: 21001
  - name: ftps-psv2
    port: 21002
    targetPort: 21002
